version: "3"

services:
  vbna_server:
    build:
      context: ./
      dockerfile: vbna_server.Dockerfile
    working_dir: /usr/src/app
    volumes:
      - ./:/usr/src/app
    restart: on-failure:5 # Countermeasure against continuous request throwing when VBNA_UPDATE_ON_BOOT is enabled
    command: uvicorn main:app --reload --host 0.0.0.0 --port 22010
    ports:
      - 22010:22010 # for internal api
    environment:
      - "VBNA_WEBHOOK_URL"
    logging:
      driver: json-file
      options:
        max-size: 1m
        max-file: "3"
  static_file_server:
    build:
      context: ./
      dockerfile: static_file_server.Dockerfile
    working_dir: /usr/src/app
    volumes:
      - ./:/usr/src/app
    restart: always
    ports:
      - 22011:22011 # for public files
    logging:
      driver: json-file
      options:
        max-size: 1m
        max-file: "3"
    depends_on:
      - vbna_server
