version: "3"

services:
  vbna_server:
    build: ./
    working_dir: /usr/src/app
    volumes:
      - ./:/usr/src/app
    command: uvicorn main:app --reload --host 0.0.0.0 --port 22010
    ports:
      - 22010:22010 # for internal api
    logging:
      driver: json-file
      options:
        max-size: 1m
        max-file: "3"
